export const LOAD_CONTACTS_START = '[CONTACT] LOAD_CONTACTS_START';
export const LOAD_CONTACTS_END = '[CONTACT] LOAD_CONTACTS_END';
export const LOAD_CONTACTS_SUCCESS = '[CONTACT] LOAD_CONTACTS_SUCCESS';
export const LOAD_CONTACTS_FAILURE = '[CONTACT] LOAD_CONTACTS_FAILURE';
export const LOAD_CONTACTS_PROGRESS = '[CONTACT] LOAD_CONTACTS_PROGRESS';

export const LOAD_SINGLE_CONTACT_START = '[CONTACT] LOAD_SINGLE_CONTACT_START';
export const LOAD_SINGLE_CONTACT_END = '[CONTACT] LOAD_SINGLE_CONTACT_END';
export const LOAD_SINGLE_CONTACT_PROGRESS =
	'[CONTACT] LOAD_SINGLE_CONTACT_PROGRESS';
export const LOAD_SINGLE_CONTACT_SUCCESS =
	'[CONTACT] LOAD_SINGLE_CONTACT_SUCCESS';
export const LOAD_SINGLE_CONTACT_FAILURE =
	'[CONTACT] LOAD_SINGLE_CONTACT_FAILURE';

export const BLOCK_CONTACT_START = '[CONTACT] BLOCK_CONTACT_START';
export const BLOCK_CONTACT_END = '[CONTACT] BLOCK_CONTACT_END';
export const BLOCK_CONTACT_PROGRESS = '[CONTACT] BLOCK_CONTACT_PROGRESS';
export const BLOCK_CONTACT_SUCCESS = '[CONTACT] BLOCK_CONTACT_SUCCESS';
export const BLOCK_CONTACT_FAILURE = '[CONTACT] BLOCK_CONTACT_FAILURE';

export const UNBLOCK_CONTACT_START = '[CONTACT] UNBLOCK_CONTACT_START';
export const UNBLOCK_CONTACT_END = '[CONTACT] UNBLOCK_CONTACT_END';
export const UNBLOCK_CONTACT_PROGRESS = '[CONTACT] UNBLOCK_CONTACT_PROGRESS';
export const UNBLOCK_CONTACT_SUCCESS = '[CONTACT] UNBLOCK_CONTACT_SUCCESS';
export const UNBLOCK_CONTACT_FAILURE = '[CONTACT] UNBLOCK_CONTACT_FAILURE';

export const REINIT_CONTACT_STATE = '[CONTACT] REINIT_CONTACT_STATE';
