export const LOAD_CHAT_START = '[CHAT] LOAD_CHAT_START';
export const LOAD_CHAT_PROGRESS = '[CHAT] LOAD_CHAT_PROGRESS';
export const LOAD_CHAT_END = '[CHAT] LOAD_CHAT_END';
export const LOAD_CHAT_SUCCESS = '[CHAT] LOAD_CHAT_SUCCESS';
export const LOAD_CHAT_FAILURE = '[CHAT] LOAD_CHAT_FAILURE';

export const SEND_MESSAGE_START = '[CHAT] SEND_MESSAGE_START';
export const SEND_MESSAGE_PROGRESS = '[CHAT] SEND_MESSAGE_PROGRESS';
export const SEND_MESSAGE_END = '[CHAT] SEND_MESSAGE_END';
export const SEND_MESSAGE_SUCCESS = '[CHAT] SEND_MESSAGE_SUCCESS';
export const SEND_MESSAGE_FAILURE = '[CHAT] SEND_MESSAGE_FAILURE';

export const DELETE_PROFILE_IMAGE_START = '[CHAT] DELETE_PROFILE_IMAGE_START';
export const DELETE_PROFILE_IMAGE_PROGRESS =
	'[CHAT] DELETE_PROFILE_IMAGE_PROGRESS';
export const DELETE_PROFILE_IMAGE_END = '[CHAT] DELETE_PROFILE_IMAGE_END';
export const DELETE_PROFILE_IMAGE_SUCCESS =
	'[CHAT] DELETE_PROFILE_IMAGE_SUCCESS';
export const DELETE_PROFILE_IMAGE_FAILURE =
	'[CHAT] DELETE_PROFILE_IMAGE_FAILURE';

export const ADD_PROFILE_IMAGE_START = '[CHAT] ADD_PROFILE_IMAGE_START';
export const ADD_PROFILE_IMAGE_END = '[CHAT] ADD_PROFILE_IMAGE_END';
export const ADD_PROFILE_IMAGE_PROGRESS = '[CHAT] ADD_PROFILE_IMAGE_PROGRESS';
export const ADD_PROFILE_IMAGE_SUCCESS = '[CHAT] ADD_PROFILE_IMAGE_SUCCESS';
export const ADD_PROFILE_IMAGE_FAILURE = '[CHAT] ADD_PROFILE_IMAGE_FAILURE';

export const REINIT_CHAT_STATE = '[CHAT] REINIT_CHAT_STATE';
