export const SEARCH_CONTACTS_START = '[SEARCH] SEARCH_CONTACTS_START';
export const SEARCH_CONTACTS_END = '[SEARCH] SEARCH_CONTACTS_END';
export const SEARCH_CONTACTS_PROGRESS = '[SEARCH] SEARCH_CONTACTS_PROGRESS';
export const SEARCH_CONTACTS_SUCCESS = '[SEARCH] SEARCH_CONTACTS_SUCCESS';
export const SEARCH_CONTACTS_FAILURE = '[SEARCH] SEARCH_CONTACTS_FAILURE';

export const REINIT_NAV_STATE = '[NAV] REINIT_NAV_STATE';
