export const CHECK_LOGIN_STATUS = '[AUTH] CHECK_LOGIN_STATUS';

export const LOGIN_START = '[AUTH] LOGIN_START';
export const LOGIN_PROGRESS = '[AUTH] LOGIN_PROGRESS';
export const LOGIN_END = '[AUTH] LOGIN_END';
export const LOGIN_SUCCESS = '[AUTH] LOGIN_SUCCESS';
export const LOGIN_FAILURE = '[AUTH] LOGIN_FAILURE';

export const GOOGLE_LOGIN_START = '[AUTH] GOOGLE_LOGIN_START';
export const GOOGLE_LOGIN_PROGRESS = '[AUTH] GOOGLE_LOGIN_PROGRESS';
export const GOOGLE_LOGIN_END = '[AUTH] GOOGLE_LOGIN_END';
export const GOOGLE_LOGIN_SUCCESS = '[AUTH] GOOGLE_LOGIN_SUCCESS';
export const GOOGLE_LOGIN_FAILURE = '[AUTH] GOOGLE_LOGIN_FAILURE';

export const REGISTER_START = '[AUTH] REGISTER_START';
export const REGISTER_PROGRESS = '[AUTH] REGISTER_PROGRESS';
export const REGISTER_END = '[AUTH] REGISTER_END';
export const REGISTER_SUCCESS = '[AUTH] REGISTER_SUCCESS';
export const REGISTER_FAILURE = '[AUTH] REGISTER_FAILURE';
export const EMAIL_VERIFICATION_POPUP_CLOSE =
	'[AUTH] EMAIL_VERIFICATION_POPUP_CLOSE';
export const ADD_CONTACT = '[AUTH] ADD_CONTACT';

export const PASSWORD_RESET_LINK_SEND_START =
	'[AUTH] PASSWORD_RESET_LINK_SEND_START';
export const PASSWORD_RESET_LINK_SEND_PROGRESS =
	'[AUTH] PASSWORD_RESET_LINK_SEND_PROGRESS';
export const PASSWORD_RESET_LINK_SEND_END =
	'[AUTH] PASSWORD_RESET_LINK_SEND_END';
export const RESET_PASSWORD_RESET_LINK_SEND_SUCCESS =
	'[AUTH] RESET_PASSWORD_RESET_LINK_SEND_SUCCESS';

export const LOG_OUT = '[AUTH] LOG_OUT';
export const LOG_OUT_SUCCESS = '[AUTH] LOG_OUT_SUCCESS';
